POST http://localhost:3001/api/recipes/6034f4b1326f952ccc9d88cb/delete 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzYXZlZFJlY2lwZXMiOltdLCJfaWQiOiI2MDM5MjY5YTEzZDlhZDA3YzQ2YmJhZjAiLCJ1c2VybmFtZSI6InRlc3R1c2VyMSIsInBhc3N3b3JkIjoiJDJiJDEwJDM3RkZTVE9FZVUuVHk3NzI3T0Z4VmVPYUI2ZS4xZGgvenBqYUlmLmpJeHdhUnhJNjNwRFdDIiwiX192IjowfQ.9lajLsIcwKyEnYTii48ZOSkBIE8lSTkFqS8i9BN2XAA