POST http://localhost:3001/api/recipes/60735b883df2a3589478efc8/delete 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImlkIjoiNjAzOTI2OWExM2Q5YWQwN2M0NmJiYWYwIiwiaWF0IjoxNjE4MTcyNzAyfQ.dq3qwN99EmWWH-vzeqPV1v4RM6SgbzarVqvG_1zeR6A