POST http://localhost:3001/api/recipes 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImlkIjoiNjA3NGM2NzkzZGEzNDM2Mzk0YjJhNWQ4IiwiaWF0IjoxNjE4MjY1NzMwfQ.xoIaoEW5R3Mk0TIbi0efaaqIJdeelriWnqVEdvVCGbg
Content-type: application/json

{
    "title": "Curry",
    "ingredients": ["chicken", "onion", "curry paste"], 
    "directions": "I love thai food :)",
    "cookTime": "60+"
}